=== CoderXiZhe/rpc/framework/core/src/main/resources/rpc-config.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!--        <!ELEMENT configuration (-->
<!--                port?,-->
<!--                appName?,-->
<!--                registry?,-->
<!--                serializeType?,-->
<!--                serializer?,-->
<!--                compressType?,-->
<!--                compressor?,-->
<!--                loadBalancer?,-->
<!--                idGenerator?)>-->
        <!ELEMENT configuration ANY>



        <!ELEMENT port ANY>
        <!ELEMENT appName ANY>
        <!ELEMENT registry EMPTY>
        <!ATTLIST registry
                url CDATA #REQUIRED>
        <!ELEMENT serializeType EMPTY>
        <!ATTLIST serializeType
                type CDATA #REQUIRED>
        <!ELEMENT serializer EMPTY>
        <!ATTLIST serializer
                class CDATA #REQUIRED>

        <!ELEMENT compressType EMPTY>
        <!ATTLIST compressType
                type CDATA #REQUIRED>
        <!ELEMENT compressor EMPTY>
        <!ATTLIST compressor
                class CDATA #REQUIRED>
        <!ELEMENT loadBalancer EMPTY>
        <!ATTLIST loadBalancer
                class CDATA #REQUIRED>
        <!ELEMENT idGenerator EMPTY>
        <!ATTLIST idGenerator
                class CDATA #REQUIRED
                dataCenterId CDATA #REQUIRED
                machineId CDATA #REQUIRED
                >



        <!--常规实体之内部实体-->
        <!ENTITY generalEntityOfInner "常规实体之内部实体">
        <!--常规实体之外部实体-->
        <!ENTITY generalEntityOfOuter SYSTEM "EntityDTD.dtd">
        <!--字符实体：参考网站https://www.teshuzifu.cn/-->
        <!ENTITY characterEntity "&#928;">
        <!--内置实体-->
        <!ENTITY buildInEntity "&lt;&amp;&gt;">
        <!--参数实体-->
        <!ENTITY % parameterEntity "id">
        <!ENTITY parameterEntityActual "%parameterEntity;">

        <!ELEMENT root (entityElementContext,entityAttribute)>
        <!ELEMENT entityElementContext (generalEntity,characterEntity,buildInEntity,parameterEntityActual)>
        <!ELEMENT generalEntity (#PCDATA)>
        <!ELEMENT characterEntity (#PCDATA)>
        <!ELEMENT buildInEntity (#PCDATA)>
        <!ELEMENT parameterEntityActual (#PCDATA)>

        <!--实体之应用于属性-->
        <!ELEMENT entityAttribute (#PCDATA)>
        <!ATTLIST entityAttribute %parameterEntity; CDATA #REQUIRED name CDATA #REQUIRED>

=== CoderXiZhe/rpc/framework/core/src/main/resources/rpc.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE configuration SYSTEM "http://rpc-config.dtd">
<configuration>

    <port>8099</port>
    <appName>rpc-default-app</appName>
    <!-- 二选一 -->
    <serializeType type="hessian"/>
    <serializer class="com.xizhe.serialize.HessianSerializer"/>
    <!-- 二选一 -->
    <compressType type="gzip"/>
    <compressor class="com.xizhe.compress.GzipCompressor"/>
    <registry url="zookeeper://127.0.0.1:2181"/>
    <loadBalancer class="com.xizhe.loadbalance.impl.RoundRobinLoadBalancer"/>
    <idGenerator class="com.xizhe.IdGenerator" dataCenterId="1" machineId="2"/>
</configuration>
